# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod/.gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: |
      docker-compose pull
    command: |
      docker-compose up -d
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
  - name: Adminer
    description: Port 8080 for the adminer
    port: 8080
    onOpen: ignore
vscode:
  extensions:
    - AmazonWebServices.aws-toolkit-vscode
    - bmewburn.vscode-intelephense-client
    - DEVSENSE.composer-php-vscode
    - DEVSENSE.phptools-vscode
    - DEVSENSE.profiler-php-vscode
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    - xdebug.php-debug
