name: Test and deploy my CDK configuration for Wordpress
on:
  push:
    branches:
      - main
    paths:
      - 'aws_config/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v3

      - name: actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install
        working-directory: ./aws_config

      - name: CDK Synth
        uses: arnaskro/aws-cdk-v2-github-actions@v2.2.1
        with:
          cdk_subcommand: 'synth'
          working_dir: './aws_config'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.DEV_AWS_REGION }}
      - name: CDK Test
        run: npm run test
        working-directory: ./aws_config
# Do not deploy until ready for production
      # - name: CDK Deploy
      #   uses: arnaskro/aws-cdk-v2-github-actions@v2.2.0
      #   with:
      #     cdk_subcommand: 'deploy'
      #     cdk_stack: 'CmsParamsStack CmsConfigStack'
      #     cdk_args: '--require-approval never'
      #     working_dir: './aws_config'
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.DEV_AWS_REGION }}
